export const FETCH_CAT_FACT = "FETCH_CAT_FACT";
export const FETCH_CAT_FACT_SUCCESS = "FETCH_CAT_FACT_SUCCESS";
export const FETCH_CAT_FACT_FAILED = "FETCH_CAT_FACT_FAILED";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
